package utils

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
)

// LeaseData identifies the info needed to generate a professional lease
type LeaseData struct {
	LandlordName string
	TenantName   string
	BuildingName string
	Address      string
	UnitNumber   string
	RentAmount   float64 // in Naira
	StartDate    string
	EndDate      string
}

// GenerateLeasePDF creates a professional lease agreement and returns the PDF as bytes
func GenerateLeasePDF(data LeaseData) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Header
	pdf.SetFont("Arial", "B", 24)
	pdf.CellFormat(0, 20, "RESIDENTIAL LEASE AGREEMENT", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// Parties
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, "1. THE PARTIES")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 6, fmt.Sprintf("This Lease Agreement is made this %s, by and between:", time.Now().Format("January 02, 2006")), "", "L", false)
	pdf.Ln(2)
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 6, "LANDLORD: "+data.LandlordName)
	pdf.Ln(6)
	pdf.Cell(0, 6, "TENANT: "+data.TenantName)
	pdf.Ln(10)

	// Property
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, "2. THE PROPERTY")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 6, fmt.Sprintf("The Landlord agrees to lease the residential unit known as %s, located at %s, within the building %s.", 
		data.UnitNumber, data.Address, data.BuildingName), "", "L", false)
	pdf.Ln(10)

	// Term
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, "3. LEASE TERM")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 6, fmt.Sprintf("The lease shall commence on %s and shall expire on %s, unless terminated earlier according to the terms of this agreement.", 
		data.StartDate, data.EndDate), "", "L", false)
	pdf.Ln(10)

	// Rent
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 10, "4. RENT PAYMENTS")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(0, 6, fmt.Sprintf("The Tenant agrees to pay a monthly rent amount of NGN %.2f (Nigerian Naira). Payments are due on the first day of each month via the Ergo platform.", 
		data.RentAmount), "", "L", false)
	pdf.Ln(10)

	// Signatures
	pdf.Ln(20)
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(90, 10, "__________________________", "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 10, "__________________________", "", 1, "L", false, 0, "")
	pdf.CellFormat(90, 10, "Landlord Signature", "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 10, "Tenant Signature", "", 1, "L", false, 0, "")

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 10, "Generated by Ergo — Property Management Redefined", "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
